version: '3'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: so1
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_START_ARGS=--accept-license
    tty: true
